import type { ChatTexts } from "quassel";

export const englishTexts: ChatTexts = {
  working: "Working ...",
  toolRunning: "running ...",
  toolStillRunning: "Tool running ...",
  toolElapsedSeconds: "{seconds}s",
  currentTool: "Tool running",
  thinkingChip: "Thinking",
  toolChip: "Tool",
  stepGroupOne: "1 step",
  stepGroupMany: "{count} steps",
  stepGroupCollapse: "Collapse",
  thinkingTitle: "Thinking",
  toolTitle: "Tool call",
  argumentsLabel: "Arguments",
  resultLabel: "Result",
  close: "Close",
  jumpToEnd: "Jump to end",
  send: "Send",
  sendIntoRun: "Send into the running turn",
  stop: "Stop",
  placeholder: "Write a message ...",
  steeringPlaceholder: "Steer the running turn ...",
  steered: "Sent into the running turn",
  detailModeTitle: "Step detail",
  detailModeOff: "answers only",
  detailModeCurrent: "current",
  detailModeIcons: "icons",
  detailModeChips: "chips",
  detailModeGrouped: "grouped",
  detailModeCompact: "one line",
  detailModeFull: "everything",
  showAllMessages: "Show intermediate replies",
  showLatestExchange: "Show latest reply between inputs",
  showTimestamps: "Show timestamps",
  hideTimestamps: "Hide timestamps",
  copyMessage: "Copy message",
  editMessage: "Edit message",
  retryMessage: "Retry",
  copyCode: "Copy code",
  copied: "Copied",
  pendingAction: "waiting for input",
  dismissAction: "Dismiss",
  actionDismissed: "dismissed",
  actionFailed: "Action failed",
  clipboardUnavailable: "The clipboard is not available",
  transcript: "Chat transcript",
  attachments: "Attachments",
  attachFiles: "Attach files",
  attachFilesHint: "Attach files (up to {count} files, {size} in total)",
  removeAttachment: "Remove {name}",
  attachmentPreparing: "Preparing ...",
  attachmentsPreparing: "Preparing attachments ...",
  attachmentReadFailed: "The file could not be read. Remove it and add it again.",
  attachmentsWhileBusy: "Wait until the input is ready again, then add the files again.",
  tooManyAttachments: "At most {count} attachments per message. Remove one first.",
  attachmentsTooLarge: "Attachments may not exceed {size} in total. Choose smaller files.",
  attachmentUnsupported: "This chat does not support {name} as {kind}. Remove the attachment.",
  attachmentUnsupportedByModel: "The model {model} does not support {name} as {kind}. Choose another model or remove the attachment.",
  attachmentKindImage: "image",
  attachmentKindVideo: "video",
  attachmentKindPdf: "PDF",
  notSent: "Not sent:",
  notSentAttachments: "({count} attachments)",
  insertUnsent: "Insert unsent input",
};
