import { Message } from "quassel";

/** Ein Verlauf für die Nur-Lesen-Schublade; die letzte Schrittzeile zeigt alle vier Zustände. */
export const transcript: Message[] = [
  {
    key: "1",
    role: "user",
    text: "Wie sieht der Energieverbrauch der letzten Woche aus?",
    closed: true,
  },
  {
    key: "2",
    role: "thinking",
    text: "Der Nutzer will eine Wochenübersicht. Ich hole die Tageswerte und rechne den Schnitt aus.",
    closed: true,
  },
  {
    key: "3",
    role: "tool",
    text: 'lade_tageswerte { bereich: "letzte Woche" }',
    closed: true,
    tool: {
      id: "t1",
      name: "lade_tageswerte",
      arguments: '{ "bereich": "letzte Woche", "einheit": "kWh" }',
      result: '{ "tage": 7, "summe": 1284, "spitze": { "tag": "Mittwoch", "wert": 231 } }',
    },
  },
  {
    key: "4",
    role: "assistant",
    text: [
      "Die letzte Woche in Kürze:",
      "",
      "- **Summe**: 1284 kWh",
      "- **Schnitt**: rund 183 kWh pro Tag",
      "- **Spitze**: Mittwoch mit 231 kWh",
      "",
      "| Tag | kWh |",
      "|---|---|",
      "| Montag | 176 |",
      "| Dienstag | 189 |",
      "| Mittwoch | 231 |",
      "| Donnerstag | 174 |",
      "",
      "Der Mittwoch fällt auf - soll ich da reinschauen?",
    ].join("\n"),
    closed: true,
  },
  {
    key: "5",
    role: "user",
    text: "Ja, bitte.",
    closed: true,
  },
  {
    key: "6",
    role: "tool",
    text: 'lade_stundenwerte { tag: "Mittwoch" }',
    closed: true,
    tool: {
      id: "t2",
      name: "lade_stundenwerte",
      arguments: '{ "tag": "Mittwoch" }',
      result: '{ "fehler": "Zeitreihe hat eine Lücke zwischen 02:00 und 04:00" }',
      isError: true,
    },
  },
  {
    key: "7",
    role: "assistant",
    text: "Beim Mittwoch gibt es eine Lücke in der Zeitreihe (02:00 bis 04:00) - die Stundenauflösung ist darum nur teilweise belastbar. Die Spitze lag am Nachmittag zwischen 14:00 und 16:00.",
    closed: true,
  },
  {
    key: "7a",
    role: "user",
    text: "Wie sieht das im Vergleich zu den Wochen davor aus?",
    closed: true,
  },
  ...Array.from({ length: 12 }, (_, index): Message => ({
    key: `7b-${index}`,
    role: "tool",
    text: `lade_tageswerte { woche: -${index + 1} }`,
    closed: true,
    tool: {
      id: `w${index}`,
      name: "lade_tageswerte",
      arguments: `{ "woche": -${index + 1}, "einheit": "kWh" }`,
      result: `{ "summe": ${1180 + ((index * 37) % 90)} }`,
    },
  })),
  {
    key: "7c",
    role: "assistant",
    text: "Über die letzten zwölf Wochen lag die Summe zwischen 1180 und 1270 kWh - die letzte Woche liegt knapp darüber.",
    closed: true,
  },
  {
    key: "8",
    role: "user",
    text: "Kannst du die Lücke schließen?",
    closed: true,
  },
  {
    key: "9",
    role: "tool",
    text: 'pruefe_ersatzquelle { tag: "Mittwoch" }',
    closed: true,
    tool: {
      id: "t3",
      name: "pruefe_ersatzquelle",
      arguments: '{ "tag": "Mittwoch" }',
      result: '{ "quelle": "zaehler_b", "abdeckung": "02:00-04:00" }',
    },
  },
  {
    key: "10",
    role: "tool",
    text: 'schreibe_ersatzwerte { quelle: "zaehler_b" }',
    closed: true,
    tool: {
      id: "t4",
      name: "schreibe_ersatzwerte",
      arguments: '{ "quelle": "zaehler_b", "tag": "Mittwoch" }',
      result: '{ "fehler": "Schreibrecht auf zaehler_b fehlt" }',
      isError: true,
    },
  },
  {
    key: "11",
    role: "tool",
    text: 'frage_rechte_an { quelle: "zaehler_b" }',
    closed: true,
    tool: {
      id: "t5",
      name: "frage_rechte_an",
      arguments: '{ "quelle": "zaehler_b" }',
    },
  },
  {
    key: "12",
    role: "thinking",
    text: "Solange die Anfrage offen ist, kann ich nur den bereinigten Tagesschnitt anbieten.",
  },
];
